[package]
name = "vine"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[dependencies]
pumpkin-protocol = { path = "../Pumpkin/crates/pumpkin-protocol" }
pumpkin-util = { path = "../Pumpkin/crates/pumpkin-util" }
pumpkin-command = { path = "../Pumpkin/crates/pumpkin-command" }
pumpkin-plugin-runtime = { path = "../Pumpkin/crates/pumpkin-plugin-runtime" }
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime", rev = "f6b3140dbb1d9b436ef523d14740292c956b0364", default-features = false, features = ["runtime", "component-model", "component-model-async", "async", "cache", "cranelift", "gc", "gc-drc", "threads", "std"] }
wasmtime-wasi = { git = "https://github.com/bytecodealliance/wasmtime", rev = "f6b3140dbb1d9b436ef523d14740292c956b0364", default-features = false, features = ["p2", "p3"] }

tokio = { version = "1.53", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
toml = { version = "1.1", features = ["parse", "display", "serde"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
thiserror = { version = "2.0" }
bytes = { version = "1.12" }
uuid = { version = "1.26", features = ["serde", "v3", "v4"] }
rand = { version = "0.10" }

# Networking & Sockets
socket2 = { version = "0.6", features = ["all"] }

# Security & Cryptography
rsa = { version = "=0.10.0-rc.18", features = ["std", "encoding"] }
sha1 = { version = "=0.11.0" }
sha2 = { version = "=0.11.0" }
hmac = { version = "=0.13.0" }
num-bigint = { version = "0.5" }
base64 = { version = "0.23" }
ed25519-dalek = { version = "3.0", default-features = false, features = ["fast"] }
hex = { version = "0.4", default-features = false, features = ["std"] }

# HTTP client for Mojang auth and telemetry
reqwest = { version = "0.13.4", default-features = false, features = ["rustls-no-provider", "json", "http2"] }

# Telemetry & System Info
sysinfo = { version = "0.39", default-features = false, features = ["system"] }

[dev-dependencies]
tempfile = "3"
axum = { version = "0.8", default-features = false, features = ["http1", "tokio"] }

[profile.release]
lto = true
codegen-units = 1
